"""add password reset model

Revision ID: 7011c69f94d4
Revises: 1566b9d6b444
Create Date: 2025-02-11 23:38:35.384446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7011c69f94d4'
down_revision: Union[str, None] = '1566b9d6b444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_column('user', 'code_theme_light')
    op.drop_column('user', 'code_theme_dark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('code_theme_dark', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('code_theme_light', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('password_resets')
    # ### end Alembic commands ###
